version: "3"
services:
  grpc-server:
    container_name: grpc-server
    build:
      context: ./app
      dockerfile: Dockerfile
    links:
      - mongo
  grpc-client:
    container_name: grpc-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
